player:
  # 死亡時に失う経験値割合(%)
  # ex)
  #     lv10になるために合計で100必要
  #     lv11になるために合計で150必要
  # lv10で死亡したとき，
  # 失う経験値 = (150 - 100) * (death_penalty / 100)
  death_penalty: 7

world:
  # 正方形の１辺の長さ
  # 実際には±0座標を中心とするので
  # min(x,z) = -(side_length/2),-(side_length/2)
  # max(x,z) = side_length/2,side_length/2
  side_length: 20000.0

# TRUEの時debug.ymlに従う
debug_mode: false


